export const WORKOUT_TYPES = [
  "bench press",
  "should press",
  "hang clean",
  "clean",
  "squat",
  "snatch",
  "hang snatch",
  "pull up",
  "single leg squat",
  "rear delt fly",
  "cable face pull",
  "leg lifts",
  "plank",
  "toe touches",
  "bicycles",
  "true bubka",
  "wipers",
  "down pressure",
  "good morning",
  "calf raises",
  "calf raises (seated)",
  "sauna",
  "creatine",
  "protein",
] as const
